### ISSUE TITLE
The successors of upstream OpenGApps

### ISSUE THREAD

**Issue by pexcn** [pexcn/gapps#11]
- https://sourceforge.net/projects/litegapps/
- https://sourceforge.net/projects/flamegapps/
- https://sourceforge.net/projects/nikgapps/
- https://bitgapps.github.io
- [MindTheGapps](http://downloads.codefi.re/jdcteam/javelinanddart/gapps)

**Comment by pexcn** [comment]
Degree of recommendation (according to simplicity and lightweight):
MindTheGapps > LiteGapps > BiTGApps > nikgapps = flamegapps

**Comment by pexcn** [comment]
In the end, I chose [MindTheGapps](https://wiki.lineageos.org/gapps), and make a lite version.

Released in https://github.com/pexcn/gapps/releases/tag/v3, the difference from the original:
- Remove useless packages
- Pick some Pixel feature configs (`/system/product/etc/sysconfig`) from LiteGapps
- Add Google Pixel Sounds

**Comment by YT-Advanced** [comment]
@pexcn Hello, I'm interested in your gapps. But I didn't know what is Pixel feature configs. Is it build.prop ?

**Comment by pexcn** [comment]
> @pexcn Hello, I'm interested in your gapps. But I didn't know what is Pixel feature configs. Is it build.prop ?

No, I don’t remember the details, probably some files under `/system/product/etc/sysconfig`.
